networks:
  dev:

services:
  postgres:
    image: postgres:17.0-alpine
    container_name: auth-service-db
    env_file: .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev


volumes:
  pgdata:
