basePath: /
definitions:
  dto.SubscriptionRequest:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  dto.SubscriptionResponse:
    properties:
      end_date:
        type: string
      id:
        type: integer
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API для управления подписками
  title: Subscription Service API
  version: "1.0"
paths:
  /subscriptions:
    get:
      consumes:
      - application/json
      description: Возвращает все подписки с пагинацией
      parameters:
      - description: Max items (default 100)
        in: query
        name: limit
        type: integer
      - description: Offset (default 0)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.SubscriptionResponse'
            type: array
        "500":
          description: failed to get subscriptions
          schema:
            type: string
      summary: Список подписок
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создаёт новую подписку пользователю
      parameters:
      - description: Subscription data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SubscriptionResponse'
        "400":
          description: invalid request
          schema:
            type: string
        "500":
          description: failed to create subscription
          schema:
            type: string
      summary: Создать подписку
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет подписку по ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: no content
          schema:
            type: string
        "400":
          description: invalid id
          schema:
            type: string
        "500":
          description: failed to delete subscription
          schema:
            type: string
      summary: Удалить подписку
      tags:
      - subscriptions
    get:
      consumes:
      - application/json
      description: Возвращает подписку по её ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SubscriptionResponse'
        "400":
          description: invalid id
          schema:
            type: string
        "500":
          description: failed to get subscription
          schema:
            type: string
      summary: Получить подписку
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Обновляет данные подписки по ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated subscription
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "204":
          description: no content
          schema:
            type: string
        "400":
          description: invalid request
          schema:
            type: string
        "500":
          description: failed to update subscription
          schema:
            type: string
      summary: Обновить подписку
      tags:
      - subscriptions
  /subscriptions/summary/{start}/{end}:
    get:
      consumes:
      - application/json
      description: Считает суммарную стоимость подписок пользователя на сервис за
        период [start; end]
      parameters:
      - description: Start date (YYYY-MM-DD)
        in: path
        name: start
        required: true
        type: string
      - description: End date (YYYY-MM-DD)
        in: path
        name: end
        required: true
        type: string
      - description: User UUID (optional)
        in: query
        name: user_id
        type: string
      - description: Service name (optional)
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: total cost
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: invalid parameters
          schema:
            type: string
        "500":
          description: failed to calculate cost
          schema:
            type: string
      summary: Общая стоимость подписок
      tags:
      - subscriptions
schemes:
- http
swagger: "2.0"
